### ISSUE TITLE
Compiling error due to mvn

### ISSUE THREAD

**Issue by chunyang-wen** [baidu/bigflow#17]
Some error happens when executing command involving `mvn`.

After I add `.m2/setting.xml`, the building process continues. I am not sure what happens.

I think there should be instructions in build documentation.

**Comment by advancedxy** [comment]
What's the error message?

And what's the content in  `~/.m2/setting.xml` or do you just touch a empty `~/.m2/setting.xml`

**Comment by chunyang-wen** [comment]
I copied setting.xml from my other projects.

**Comment by advancedxy** [comment]
Then what's the error message?

You can 
```
cd flume/runtime/scala
mvn -DskipTests package
```
to execute mvn command.

Please attach the error message with your `~/.m2/setting.xml` removed if still presented.

**Comment by chunyang-wen** [comment]
I am closing this because I have successfully built it and the unit tests run correctly.

Maybe we should record it if someone meets similar building problem.

**Comment by advancedxy** [comment]
Ok, then. I added a `building problem` to this issue. 

My guess is that you are in restricted network/environment. `mvn` can not be used directly with default settings. 

If others met similar problem, please check that your `mvn` can work normally.
