### ISSUE TITLE
Online demo isn't working

### ISSUE THREAD

**Issue by Justineo** [baidu/bigflow#25]
Server responded with `HTTP ERROR 500`.

**Comment by acmol** [comment]
We have declared that we don't have any defences for any attack in this online demo virtual machine, but any effects by the attacking will be restored by the machine reseting.

And somebody is so boring that he want to show his strength by attacking a defenceless machine, so he deleted all the files.

We will reset the machine soon and set the files we don't want to be removed  into readonly mode (chowned to root user). Maybe automaticlly and totally resettings are required in the future.

**Comment by himdd** [comment]
Already reset

**Comment by acmol** [comment]
Why is someone so boring that keep doing harmful thing to the online demo pages...
So, @himdd maybe we should reset the machine every day from the snapshot.
